parse("mp_damagefactor 1000")

dofile("sys/lua/Sagos/awp_grey Sagos.lua")
--dofile("sys/lua/Sagos/ServeR ControL 4.5.lua")
--dofile("sys/lua/Sagos/Fala3.lua")
--dofile("sys/lua/Sagos/Battle Royale.lua")
--dofile("sys/lua/Sagos/building.lua")
--dofile("sys/lua/Sagos/Flamethrower Realista.lua")
--dofile("sys/lua/Sagos/Cerbex.lua")
--dofile("sys/lua/Sagos/Enderman.lua")
--dofile("sys/lua/Sagos/LoL.lua")
--dofile("sys/lua/Sagos/WasZay.lua")
--dofile("sys/lua/Sagos/Defender.lua")
--dofile("sys/lua/Sagos/Seta.lua")
--dofile("sys/lua/Sagos/testes.lua")
--dofile("sys/lua/Sagos/Kamikaze.lua")
--dofile("sys/lua/Sagos/Jumper.lua")
--dofile("sys/lua/Sagos/Minhoca de Fogo 2.lua")
--dofile("sys/lua/Sagos/Slow Motion.lua")
--dofile("sys/lua/Sagos/Regenerar.lua")
--dofile("sys/lua/Sagos/Pega-Pega.lua")
--dofile("sys/lua/Sagos/Pac-man.lua")
--dofile("sys/lua/Sagos/mini map.lua")
--dofile("sys/lua/Sagos/Conquistas.lua")